# Generated by Django 4.2.14 on 2026-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscprocurement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetemplate',
            name='creator',
        ),
        migrations.AddField(
            model_name='costestimatetemplatebody',
            name='version',
            field=models.IntegerField(db_column='Version', default=1, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='costestimatetemplatehead',
            name='status',
            field=models.IntegerField(choices=[(0, '未确认'), (1, '已确认'), (2, '作废')], db_column='Status', default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='costestimatetemplatehead',
            name='version',
            field=models.IntegerField(db_column='Version', default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='costestimatetemplatebody',
            name='template_no',
            field=models.CharField(db_column='TemplateNo', max_length=20, verbose_name='模板编号'),
        ),
        migrations.AlterField(
            model_name='costestimatetemplatehead',
            name='template_no',
            field=models.CharField(db_column='TemplateNo', db_index=True, max_length=20, verbose_name='模板编号'),
        ),
        migrations.AddIndex(
            model_name='costestimatetemplatebody',
            index=models.Index(fields=['template_no', 'version'], name='idx_cost_template_body_no_ver'),
        ),
        migrations.AddIndex(
            model_name='costestimatetemplatehead',
            index=models.Index(fields=['template_no', 'version'], name='idx_cost_template_head_no_ver'),
        ),
        migrations.AddConstraint(
            model_name='costestimatetemplatehead',
            constraint=models.UniqueConstraint(fields=('template_no', 'version'), name='uq_cost_template_head_no_ver'),
        ),
        migrations.DeleteModel(
            name='PriceTemplate',
        ),
    ]
