# Generated by Django 4.2.14 on 2026-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscprocurement', '0004_inquiry_template_version_inquirymaterialcost_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='template_version',
            field=models.IntegerField(db_column='TemplateVersion', default=1, help_text='与 template 共同锁定成本估算模板主表版本（CostEstimateTemplateHead.version）；发布与供应商报价结构均以此为准。', verbose_name='模板版本号'),
        ),
    ]
