# Generated by Django 4.2.14 on 2026-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscprocurement', '0006_inquiry_bid_end_time_inquiry_bid_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misclowpriceheader',
            name='item_no',
            field=models.CharField(db_column='ItemNo', help_text='根据成本类别获取询价单对应子表数据行，材料类别 - 材料成本的产品料号 part_id, 加工类别 - 加工工站 process_station', max_length=100, verbose_name='项次名'),
        ),
    ]
