# Generated by Django 4.2.14 on 2026-04-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscprocurement', '0007_alter_misclowpriceheader_item_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscProcMaterialMinPrices',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('part_id', models.CharField(db_column='partid', max_length=50, verbose_name='采购价料号')),
                ('material_spec', models.CharField(db_column='material_spec', max_length=20, verbose_name='材料规格')),
                ('currency_code', models.CharField(db_column='currency_code', max_length=50, verbose_name='货币代码')),
                ('item_num', models.CharField(db_column='item_num', max_length=20, verbose_name='项次名')),
                ('lowest_value', models.CharField(db_column='lowest_value', max_length=20, verbose_name='最低值')),
                ('source_number', models.CharField(db_column='source_number', max_length=50, verbose_name='报价来源单号')),
                ('quotation_time', models.DateTimeField(db_column='quotation_time', verbose_name='报价时间')),
            ],
            options={
                'verbose_name': '杂采材料制程最低价信息表',
                'verbose_name_plural': '杂采材料制程最低价信息表',
                'db_table': 'pis_misc_proc_material_min_prices',
                'ordering': ('-create_datetime', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MiscProcProcessingMinPrices',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('part_id', models.CharField(db_column='partid', max_length=50, verbose_name='采购件料号')),
                ('currency_code', models.CharField(db_column='currencycode', max_length=50, verbose_name='货币代码')),
                ('lowest_value', models.CharField(db_column='lowest_vaule', max_length=20, verbose_name='加工费用最低价')),
                ('source_number', models.CharField(blank=True, db_column='sourcenumber', max_length=50, null=True, verbose_name='报价来源单号')),
                ('quotation_time', models.DateTimeField(blank=True, db_column='quotationtime', null=True, verbose_name='报价时间')),
            ],
            options={
                'verbose_name': '杂采加工费用最低价信息表',
                'verbose_name_plural': '杂采加工费用最低价信息表',
                'db_table': 'pis_misc_proc_processing_min_prices',
                'ordering': ('-create_datetime', 'id'),
            },
        ),
        migrations.RenameIndex(
            model_name='inquirymaterialcost',
            new_name='pis_misc_pr_PartId_1213f3_idx',
            old_name='pis_proc_in_PartId_4bedee_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiryothercost',
            new_name='pis_misc_pr_PartId_d3323e_idx',
            old_name='pis_proc_in_PartId_33e9d8_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiryprocesscost',
            new_name='pis_misc_pr_PartId_cebba1_idx',
            old_name='pis_proc_in_PartId_65ad97_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiryprofitcost',
            new_name='pis_misc_pr_PartId_313c85_idx',
            old_name='pis_proc_in_PartId_aaa0eb_idx',
        ),
        migrations.AddField(
            model_name='costestimatetemplatehead',
            name='template_name_en',
            field=models.CharField(blank=True, db_column='TemplateNameEn', max_length=50, null=True, verbose_name='模板英文名'),
        ),
        migrations.AddField(
            model_name='costestimatetemplatehead',
            name='template_name_zh_tw',
            field=models.CharField(blank=True, db_column='TemplateNameZhTw', max_length=50, null=True, verbose_name='模板繁体名'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='询价单英文名'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title_zh_tw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='询价单繁体名'),
        ),
        migrations.AddField(
            model_name='miscprocurementmaterialinfo',
            name='materialtype_en',
            field=models.CharField(blank=True, help_text='材质英文名', max_length=50, null=True, verbose_name='材质英文名'),
        ),
        migrations.AddField(
            model_name='miscprocurementmaterialinfo',
            name='materialtype_zh_tw',
            field=models.CharField(blank=True, help_text='材质繁体名', max_length=50, null=True, verbose_name='材质繁体名'),
        ),
        migrations.AddField(
            model_name='miscprocurementstationinfo',
            name='stationname_en',
            field=models.CharField(blank=True, help_text='工站英文名', max_length=50, null=True, verbose_name='工站英文名'),
        ),
        migrations.AddField(
            model_name='miscprocurementstationinfo',
            name='stationname_zh_tw',
            field=models.CharField(blank=True, help_text='工站繁体名', max_length=50, null=True, verbose_name='工站繁体名'),
        ),
        migrations.AlterField(
            model_name='misclowpricedetail',
            name='item_no',
            field=models.CharField(choices=[('1', '重量'), ('2', '单价')], db_column='ItemNo', help_text='策采：重量、损耗、单价；杂采：重量、单价', max_length=100, verbose_name='项次名'),
        ),
        migrations.AlterField(
            model_name='misclowpricedetail',
            name='souce_no',
            field=models.CharField(db_column='SouceNo', help_text='重量/单价取最小值时对应报价单单号；单价来自杂采材料信息时存交易厂区代码', max_length=200, verbose_name='来源单号(报价单号或交易厂区)'),
        ),
        migrations.AlterField(
            model_name='misclowpriceheader',
            name='souce_no',
            field=models.CharField(blank=True, db_column='SouceNo', max_length=200, null=True, verbose_name='来源单号(报价单&询价单)'),
        ),
        migrations.AlterField(
            model_name='rfqoperationlogs',
            name='operation_type',
            field=models.CharField(choices=[(1, '询价单创建'), (2, '询价单确认'), (3, '询价单发布'), (4, '询价单还原'), (5, '报价截止'), (6, '供应商报价'), (7, '比议价'), (8, '议价审核提交'), (9, '议价审核完成'), (10, '议价审核驳回')], db_column='OperationType', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='pis_misc_proc_inquiry_master',
        ),
        migrations.AlterModelTable(
            name='inquiryattachment',
            table='pis_misc_proc_inquiry_attachment',
        ),
        migrations.AlterModelTable(
            name='inquirymaterialcost',
            table='pis_misc_proc_inquiry_material_cost',
        ),
        migrations.AlterModelTable(
            name='inquiryothercost',
            table='pis_misc_proc_inquiry_other_cost',
        ),
        migrations.AlterModelTable(
            name='inquiryprocesscost',
            table='pis_misc_proc_inquiry_process_cost',
        ),
        migrations.AlterModelTable(
            name='inquiryprofitcost',
            table='pis_misc_proc_inquiry_profit_cost',
        ),
        migrations.AlterModelTable(
            name='inquirysupplier',
            table='pis_misc_proc_inquiry_supplier',
        ),
        migrations.AddField(
            model_name='miscprocprocessingminprices',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='miscprocmaterialminprices',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='miscprocprocessingminprices',
            index=models.Index(fields=['part_id', 'currency_code'], name='pis_misc_pr_partid_116944_idx'),
        ),
        migrations.AddIndex(
            model_name='miscprocmaterialminprices',
            index=models.Index(fields=['part_id', 'material_spec', 'currency_code', 'item_num'], name='pis_misc_pr_partid_0a5142_idx'),
        ),
    ]
