# Generated by Django 4.2.14 on 2026-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(blank=True, help_text='菜单名称(English)', max_length=64, null=True, verbose_name='菜单名称(English)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_zh_tw',
            field=models.CharField(blank=True, help_text='菜单名称(繁體中文)', max_length=64, null=True, verbose_name='菜单名称(繁體中文)'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='name_en',
            field=models.CharField(blank=True, help_text='名称(English)', max_length=64, null=True, verbose_name='名称(English)'),
        ),
        migrations.AddField(
            model_name='menubutton',
            name='name_zh_tw',
            field=models.CharField(blank=True, help_text='名称(繁體中文)', max_length=64, null=True, verbose_name='名称(繁體中文)'),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, default='zh-cn', help_text='界面语言', max_length=10, null=True, verbose_name='界面语言'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='菜单名称(默认语言)', max_length=64, verbose_name='菜单名称(默认)'),
        ),
    ]
