# Generated by Django 4.2.14 on 2026-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_fill_menu_i18n_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='title_en',
            field=models.CharField(blank=True, help_text='标题(English)', max_length=50, null=True, verbose_name='标题(English)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='title_zh_tw',
            field=models.CharField(blank=True, help_text='标题(繁體中文)', max_length=50, null=True, verbose_name='标题(繁體中文)'),
        ),
    ]
