# Generated by Django 4.2.14 on 2026-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('company_code', models.CharField(help_text='公司代码', max_length=20, verbose_name='公司代码')),
                ('company_name', models.CharField(blank=True, help_text='公司全称', max_length=100, null=True, verbose_name='公司全称')),
                ('company_short_name', models.CharField(blank=True, help_text='公司简称', max_length=50, null=True, verbose_name='公司简称')),
                ('company_address', models.CharField(blank=True, help_text='公司地址', max_length=500, null=True, verbose_name='公司地址')),
                ('status', models.IntegerField(default=1, help_text='可用状态(1可用0不可用)', verbose_name='可用状态')),
                ('createuser', models.CharField(blank=True, help_text='创建人员', max_length=20, null=True, verbose_name='创建人员')),
                ('updateuser', models.CharField(blank=True, help_text='更新人员', max_length=20, null=True, verbose_name='更新人员')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'db_table': 'pis_company',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('currencyname', models.CharField(help_text='货币名称', max_length=50, verbose_name='货币名称')),
                ('currencycode', models.CharField(blank=True, help_text='货币代码', max_length=20, null=True, verbose_name='货币代码')),
                ('currencysymbol', models.CharField(help_text='货币符号', max_length=10, verbose_name='货币符号')),
                ('factory', models.CharField(blank=True, help_text='交易厂区(公司)', max_length=10, null=True, verbose_name='交易厂区')),
                ('tax', models.DecimalField(decimal_places=2, help_text='税率', max_digits=5, verbose_name='税率')),
                ('status', models.IntegerField(default=1, help_text='可用状态(1可用0不可用)', verbose_name='可用状态')),
            ],
            options={
                'verbose_name': '币别税率',
                'verbose_name_plural': '币别税率',
                'db_table': 'pis_currencies',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('company_code', models.CharField(blank=True, help_text='交易厂区(公司)', max_length=10, null=True, verbose_name='交易厂区')),
                ('supplier_id', models.CharField(help_text='供应商唯一ID', max_length=20, unique=True, verbose_name='供应商唯一ID')),
                ('supplier_name', models.CharField(help_text='供应商全称', max_length=100, verbose_name='供应商全称')),
                ('supplier_short_name', models.CharField(help_text='供应商简称', max_length=50, verbose_name='供应商简称')),
                ('vendor_type', models.CharField(blank=True, help_text='厂商性质', max_length=20, null=True, verbose_name='厂商性质')),
                ('payment_terms', models.CharField(blank=True, help_text='付款条件', max_length=20, null=True, verbose_name='付款条件')),
                ('transaction_currency', models.CharField(blank=True, help_text='交易货币', max_length=20, null=True, verbose_name='交易货币')),
                ('incoterms', models.CharField(blank=True, help_text='国际条款', max_length=20, null=True, verbose_name='国际条款')),
                ('supplier_level', models.CharField(blank=True, help_text='供应商等级', max_length=10, null=True, verbose_name='供应商等级')),
                ('contact_person', models.CharField(help_text='联络人', max_length=20, verbose_name='联络人')),
                ('contact_phone', models.CharField(help_text='联络人电话', max_length=20, verbose_name='联络人电话')),
                ('contact_email', models.CharField(help_text='联络人邮箱(账号)', max_length=50, verbose_name='联络人邮箱')),
                ('country', models.CharField(help_text='国家(如TW,CN)', max_length=20, verbose_name='国家')),
                ('province', models.CharField(help_text='省州', max_length=20, verbose_name='省州')),
                ('city', models.CharField(blank=True, help_text='城市', max_length=20, null=True, verbose_name='城市')),
                ('address', models.CharField(blank=True, help_text='详细地址', max_length=500, null=True, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, help_text='邮递区号', max_length=20, null=True, verbose_name='邮递区号')),
                ('status', models.IntegerField(default=1, help_text='可用状态(1可用0不可用)', verbose_name='可用状态')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
                'db_table': 'pis_suppliers',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('unitname', models.CharField(help_text='计量单位名称', max_length=50, verbose_name='计量单位名称')),
                ('unitcode', models.CharField(blank=True, help_text='计量单位代码', max_length=20, null=True, verbose_name='计量单位代码')),
                ('status', models.IntegerField(default=1, help_text='可用状态(1可用0不可用)', verbose_name='可用状态')),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
                'db_table': 'pis_units',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
