# Generated by Django 4.2.14 on 2026-03-25 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNoRule',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('company_code', models.CharField(help_text='交易厂区(公司)', max_length=20, verbose_name='交易厂区')),
                ('rule_code', models.CharField(choices=[('miscQTS', '杂采报价单'), ('miscRFS', '杂采询价单')], help_text='标识一组单号规则', max_length=50, verbose_name='生成单据标识号')),
                ('reset_cycle', models.CharField(choices=[('yy', 'YY'), ('yyyy', 'YYYY'), ('yymm', 'YYMM'), ('yyyymm', 'YYYYMM'), ('yymmdd', 'YYMMDD'), ('yyyymmdd', 'YYYYMMDD')], help_text='重置粒度', max_length=16, verbose_name='流水码重置类别')),
                ('prefix', models.CharField(blank=True, help_text='单据开头固定字符', max_length=20, null=True, verbose_name='单据头')),
                ('factory_code', models.CharField(blank=True, help_text='厂区区分码', max_length=20, null=True, verbose_name='厂区区分码')),
                ('seq_length', models.IntegerField(default=4, help_text='流水码长度', verbose_name='流水码长度')),
                ('createuser', models.CharField(blank=True, help_text='单据创建人', max_length=50, null=True, verbose_name='单据创建人')),
                ('updateuser', models.CharField(blank=True, help_text='单据修改人', max_length=50, null=True, verbose_name='单据修改人')),
                ('sequence_date', models.CharField(blank=True, help_text='与 reset_cycle 对应的日期段（如 yymmdd→260324）；新建/改重置类别时由服务端写入', max_length=12, null=True, verbose_name='流水日期')),
                ('prev_sequence', models.IntegerField(default=0, help_text='上一笔已成功发放的流水号；未发过为 0，与「下一流水码」相差 1', verbose_name='上一流水码')),
                ('current_sequence', models.IntegerField(default=1, help_text='下一笔待发流水号；新建/重置周期后为 1，每次取号成功后 +1', verbose_name='下一流水码')),
                ('last_generate_user', models.CharField(blank=True, help_text='最后产生人', max_length=50, null=True, verbose_name='单据最后产生人')),
                ('last_generate_time', models.DateTimeField(blank=True, help_text='最后产生时间', null=True, verbose_name='单据最后产生时间')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统单号规则',
                'verbose_name_plural': '系统单号规则',
                'db_table': 'pis_system_no_rules',
                'ordering': ('-create_datetime',),
                'unique_together': {('company_code', 'rule_code')},
            },
        ),
    ]
