# Generated by Django 4.2.14 on 2026-04-08 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0004_emailnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name_en',
            field=models.CharField(blank=True, help_text='公司全称英文', max_length=100, null=True, verbose_name='公司全称英文'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_zh_tw',
            field=models.CharField(blank=True, help_text='公司全称繁体', max_length=100, null=True, verbose_name='公司全称繁体'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_name_en',
            field=models.CharField(blank=True, help_text='公司简称英文', max_length=50, null=True, verbose_name='公司简称英文'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_short_name_zh_tw',
            field=models.CharField(blank=True, help_text='公司简称繁体', max_length=50, null=True, verbose_name='公司简称繁体'),
        ),
        migrations.AddField(
            model_name='currency',
            name='currencyname_en',
            field=models.CharField(blank=True, help_text='货币英文名', max_length=50, null=True, verbose_name='货币英文名'),
        ),
        migrations.AddField(
            model_name='currency',
            name='currencyname_zh_tw',
            field=models.CharField(blank=True, help_text='货币繁体名', max_length=50, null=True, verbose_name='货币繁体名'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name_en',
            field=models.CharField(blank=True, help_text='供应商全称英文', max_length=100, null=True, verbose_name='供应商全称英文'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name_zh_tw',
            field=models.CharField(blank=True, help_text='供应商全称繁体', max_length=100, null=True, verbose_name='供应商全称繁体'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_short_name_en',
            field=models.CharField(blank=True, help_text='供应商简称英文', max_length=50, null=True, verbose_name='供应商简称英文'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_short_name_zh_tw',
            field=models.CharField(blank=True, help_text='供应商简称繁体', max_length=50, null=True, verbose_name='供应商简称繁体'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unitname_en',
            field=models.CharField(blank=True, help_text='计量单位英文名', max_length=50, null=True, verbose_name='计量单位英文名'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unitname_zh_tw',
            field=models.CharField(blank=True, help_text='计量单位繁体名', max_length=50, null=True, verbose_name='计量单位繁体名'),
        ),
    ]
