# Generated by Django 4.2.14 on 2026-03-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationMaster',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('quotation_no', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='报价单单号')),
                ('inquiry_no', models.CharField(db_index=True, help_text='报价单关联的询价单单号', max_length=20, verbose_name='询价单单号')),
                ('supplier_code', models.CharField(max_length=20, verbose_name='供应商代码')),
                ('supplier_name', models.CharField(max_length=20, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人电话')),
                ('contact_email', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人邮件')),
                ('quote_deadline', models.CharField(blank=True, max_length=20, null=True, verbose_name='报价截止时间')),
                ('delivery_days', models.IntegerField(blank=True, null=True, verbose_name='交货周期')),
                ('payment_method', models.IntegerField(blank=True, choices=[(1, '月结30天'), (2, '月结60天'), (3, '货到付款'), (4, '预付30%，余款次月结')], null=True, verbose_name='付款方式')),
                ('status', models.IntegerField(blank=True, choices=[(1, '待报价'), (2, '已报价'), (3, '已过期')], default=1, help_text='1 待报价 2 已报价 3 已过期；置为已报价请走供应商端 POST quotation_master/{id}/submit/', null=True, verbose_name='状态')),
                ('is_awarded', models.IntegerField(blank=True, choices=[(0, '未中标'), (1, '已中标')], default=0, null=True, verbose_name='报价中标否')),
                ('createuser', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员')),
                ('creattime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('quoteuser', models.CharField(blank=True, max_length=20, null=True, verbose_name='报价人员')),
                ('quotetime', models.DateTimeField(blank=True, help_text='正式提交报价时由 submit 接口写入当前时间', null=True, verbose_name='报价时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='报价说明及备注')),
            ],
            options={
                'verbose_name': '杂采报价单主表',
                'verbose_name_plural': '杂采报价单主表',
                'db_table': 'pis_sup_quotation_master',
                'ordering': ('-creattime', '-autoid'),
            },
        ),
        migrations.CreateModel(
            name='QuotationProfit',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('tax_rate', models.DecimalField(blank=True, db_column='tax_rate', decimal_places=4, max_digits=12, null=True, verbose_name='税率')),
                ('profit_rate', models.DecimalField(blank=True, db_column='profit_rate', decimal_places=4, max_digits=12, null=True, verbose_name='利润率')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='profit_costs', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-税率利润明细表',
                'verbose_name_plural': '杂采报价单-税率利润明细表',
                'db_table': 'pis_sup_quotation_profit',
                'ordering': ('autoid',),
                'indexes': [models.Index(fields=['part_id'], name='pis_sup_quo_Partid_b34018_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotationProcess',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('process_station', models.CharField(blank=True, db_column='process_station', max_length=20, null=True, verbose_name='加工工站')),
                ('unit', models.DecimalField(blank=True, db_column='Unit', decimal_places=4, max_digits=12, null=True, verbose_name='单位')),
                ('unit_rate', models.DecimalField(blank=True, db_column='UnitRate', decimal_places=4, max_digits=12, null=True, verbose_name='费率')),
                ('process_qty', models.CharField(blank=True, db_column='ProcessQty', max_length=20, null=True, verbose_name='加工计量')),
                ('process_price', models.DecimalField(blank=True, db_column='ProcessPrice', decimal_places=2, max_digits=10, null=True, verbose_name='加工费用')),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=100, null=True, verbose_name='备注')),
                ('option_json', models.TextField(blank=True, db_column='OptionJson', null=True, verbose_name='可选扩展信息')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='process_costs', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-加工成本明细表',
                'verbose_name_plural': '杂采报价单-加工成本明细表',
                'db_table': 'pis_sup_quotation_process',
                'ordering': ('autoid',),
                'indexes': [models.Index(fields=['part_id'], name='pis_sup_quo_Partid_e14a9f_idx')],
                'unique_together': {('quotation_no', 'part_id', 'process_station')},
            },
        ),
        migrations.CreateModel(
            name='QuotationOther',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('packaging_cost', models.DecimalField(blank=True, db_column='packaging_cost', decimal_places=4, max_digits=12, null=True, verbose_name='包装费用')),
                ('transportation_cost', models.DecimalField(blank=True, db_column='transportation_cost', decimal_places=4, max_digits=12, null=True, verbose_name='运输费用')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='other_costs', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-其他费用明细表',
                'verbose_name_plural': '杂采报价单-其他费用明细表',
                'db_table': 'pis_sup_quotation_other',
                'ordering': ('autoid',),
                'indexes': [models.Index(fields=['part_id'], name='pis_sup_quo_Partid_f50af0_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotationMaterial',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('material_spec', models.CharField(db_column='material_spec', max_length=20, verbose_name='材料规格')),
                ('length', models.CharField(blank=True, db_column='Length', max_length=10, null=True, verbose_name='长')),
                ('width', models.CharField(blank=True, db_column='Width', max_length=10, null=True, verbose_name='宽')),
                ('height', models.CharField(blank=True, db_column='Height', max_length=10, null=True, verbose_name='高')),
                ('unit_price', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('qty', models.IntegerField(blank=True, db_column='qty', null=True, verbose_name='数量')),
                ('specific_gravity', models.CharField(blank=True, db_column='SpecificGravity', max_length=10, null=True, verbose_name='比重')),
                ('material_cost', models.DecimalField(blank=True, db_column='material_cost', decimal_places=4, max_digits=12, null=True, verbose_name='材料费用')),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=100, null=True, verbose_name='备注')),
                ('option_json', models.TextField(blank=True, db_column='OptionJson', null=True, verbose_name='可选扩展信息')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-材料成本明细表',
                'verbose_name_plural': '杂采报价单-材料成本明细表',
                'db_table': 'pis_sup_quotation_material',
                'ordering': ('autoid',),
                'indexes': [models.Index(fields=['part_id'], name='pis_sup_quo_Partid_cf933e_idx')],
                'unique_together': {('quotation_no', 'part_id', 'material_spec')},
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('product_name', models.CharField(db_column='product_name', max_length=20, verbose_name='产品名称')),
                ('unit', models.CharField(db_column='unit', max_length=10, verbose_name='计量单位')),
                ('qty', models.IntegerField(db_column='qty', verbose_name='采购数量')),
                ('is_bom', models.IntegerField(db_column='IsBom', verbose_name='是否成本结构')),
                ('unit_price', models.DecimalField(blank=True, db_column='unit_price', decimal_places=4, max_digits=12, null=True, verbose_name='标准品单价')),
                ('product_cost', models.DecimalField(blank=True, db_column='product_cost', decimal_places=4, max_digits=12, null=True, verbose_name='标准品总价')),
                ('total_material_cost', models.DecimalField(blank=True, db_column='total_material_cost', decimal_places=4, max_digits=12, null=True, verbose_name='材料成本合计')),
                ('total_processing_cost', models.DecimalField(blank=True, db_column='total_processing_cost', decimal_places=4, max_digits=12, null=True, verbose_name='加工成本合计')),
                ('total_other_expense', models.DecimalField(blank=True, db_column='total_other_expense', decimal_places=4, max_digits=12, null=True, verbose_name='其他费用合计')),
                ('total_opex_amt', models.DecimalField(blank=True, db_column='total_opex_amt', decimal_places=4, max_digits=12, null=True, verbose_name='管销研费用')),
                ('profit_rate', models.DecimalField(blank=True, db_column='profit_rate', decimal_places=4, max_digits=12, null=True, verbose_name='利润')),
                ('total_price_excl_tax', models.DecimalField(blank=True, db_column='total_price_excl_tax', decimal_places=4, max_digits=12, null=True, verbose_name='不含税总价')),
                ('tax_rate', models.DecimalField(blank=True, db_column='tax_rate', decimal_places=4, max_digits=12, null=True, verbose_name='税费')),
                ('total_price_incl_tax', models.DecimalField(blank=True, db_column='total_price_incl_tax', decimal_places=4, max_digits=12, null=True, verbose_name='含税总价')),
                ('is_awarded', models.IntegerField(blank=True, choices=[(0, '未中标'), (1, '中标')], db_column='is_awarded', null=True, verbose_name='报价中标否')),
                ('winning_bid_price', models.DecimalField(blank=True, db_column='winning_bid_price', decimal_places=4, max_digits=12, null=True, verbose_name='中标价格')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-上阶物料明细表',
                'verbose_name_plural': '杂采报价单-上阶物料明细表',
                'db_table': 'pis_sup_quot_items',
                'ordering': ('autoid',),
                'indexes': [models.Index(fields=['part_id'], name='pis_sup_quo_Partid_99a155_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('autoid', models.BigAutoField(db_column='autoId', primary_key=True, serialize=False, verbose_name='自增ID')),
                ('part_id', models.CharField(db_column='Partid', max_length=50, verbose_name='产品料号')),
                ('file_name', models.CharField(db_column='file_name', max_length=20, verbose_name='文件名称')),
                ('file_path', models.CharField(blank=True, db_column='file_path', max_length=20, null=True, verbose_name='文件路径')),
                ('uploadtime', models.CharField(blank=True, max_length=20, null=True, verbose_name='上传时间')),
                ('uploaduser', models.CharField(blank=True, max_length=20, null=True, verbose_name='上传人员')),
                ('quotation_no', models.ForeignKey(db_column='quotation_no', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pissupplier.quotationmaster', to_field='quotation_no', verbose_name='报价单单号')),
            ],
            options={
                'verbose_name': '杂采报价单-附件关联表',
                'verbose_name_plural': '杂采报价单-附件关联表',
                'db_table': 'pis_sup_quotation_attachment',
                'ordering': ('-autoid',),
                'unique_together': {('quotation_no', 'part_id', 'file_name')},
            },
        ),
    ]
