# Generated by Django 4.2.14 on 2026-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pissupplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaster',
            name='validity_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='有效天数'),
        ),
        migrations.AlterField(
            model_name='quotationprocess',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=20, null=True, verbose_name='单位'),
        ),
    ]
