# Generated by Django 4.2.14 on 2026-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pissupplier', '0002_quotationmaster_validity_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaterial',
            name='weight',
            field=models.DecimalField(blank=True, db_column='Weight', decimal_places=4, max_digits=12, null=True, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='quotationattachment',
            name='file_name',
            field=models.CharField(db_column='file_name', max_length=100, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='quotationattachment',
            name='file_path',
            field=models.CharField(blank=True, db_column='file_path', max_length=200, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='quotationmaster',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '待报价'), (2, '报价中'), (3, '已报价'), (4, '已过期')], default=1, help_text='1 待报价 2 已报价 3 已过期；置为已报价请走供应商端 POST quotation_master/{id}/submit/', null=True, verbose_name='状态'),
        ),
    ]
