# Generated by Django 4.2.14 on 2026-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pissupplier', '0003_quotationmaterial_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaster',
            name='bid_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投标截止时间'),
        ),
        migrations.AddField(
            model_name='quotationmaster',
            name='bid_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投标开始时间'),
        ),
        migrations.AddField(
            model_name='quotationmaster',
            name='buying_method',
            field=models.IntegerField(blank=True, choices=[(1, '询价'), (2, '招标')], null=True, verbose_name='采购方式（寻源方式）'),
        ),
    ]
