# Generated by Django 4.2.14 on 2026-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pissupplier', '0004_quotationmaster_bid_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationmaster',
            name='quote_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报价截止时间'),
        ),
        migrations.AlterField(
            model_name='quotationmaster',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '待报价'), (2, '报价中'), (3, '已报价'), (4, '已过期')], default=1, help_text='1 待报价 2 报价中 3 已报价 4 已过期；置为已报价请走 POST quotation_master/{id}/submit/；超时批量置过期及询价单收口见 sync_expired / Inquiry.sync_to_quote_closed_when_no_open_quotations；名单内供应商均已提交见 submit 与 Inquiry.sync_to_quote_closed_when_all_suppliers_quoted。', null=True, verbose_name='状态'),
        ),
    ]
