# Generated by Django 4.2.14 on 2026-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pissupplier', '0005_alter_quotationmaster_quote_deadline_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quotationitem',
            new_name='pis_misc_su_Partid_526e30_idx',
            old_name='pis_sup_quo_Partid_99a155_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationmaterial',
            new_name='pis_misc_su_Partid_8d3a7c_idx',
            old_name='pis_sup_quo_Partid_cf933e_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationother',
            new_name='pis_misc_su_Partid_68c79f_idx',
            old_name='pis_sup_quo_Partid_f50af0_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationprocess',
            new_name='pis_misc_su_Partid_28aa7a_idx',
            old_name='pis_sup_quo_Partid_e14a9f_idx',
        ),
        migrations.RenameIndex(
            model_name='quotationprofit',
            new_name='pis_misc_su_Partid_e7fb57_idx',
            old_name='pis_sup_quo_Partid_b34018_idx',
        ),
        migrations.AddField(
            model_name='quotationmaster',
            name='supplier_name_en',
            field=models.CharField(blank=True, help_text='供应商英文名', max_length=20, null=True, verbose_name='供应商英文名'),
        ),
        migrations.AddField(
            model_name='quotationmaster',
            name='supplier_name_zh_tw',
            field=models.CharField(blank=True, help_text='供应商繁体名', max_length=20, null=True, verbose_name='供应商繁体名'),
        ),
        migrations.AlterModelTable(
            name='quotationattachment',
            table='pis_misc_sup_quotation_attachment',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='pis_misc_sup_quot_items',
        ),
        migrations.AlterModelTable(
            name='quotationmaster',
            table='pis_misc_sup_quotation_master',
        ),
        migrations.AlterModelTable(
            name='quotationmaterial',
            table='pis_misc_sup_quotation_material',
        ),
        migrations.AlterModelTable(
            name='quotationother',
            table='pis_misc_sup_quotation_other',
        ),
        migrations.AlterModelTable(
            name='quotationprocess',
            table='pis_misc_sup_quotation_process',
        ),
        migrations.AlterModelTable(
            name='quotationprofit',
            table='pis_misc_sup_quotation_profit',
        ),
    ]
