# Form implementation generated from reading ui file 'dvadmin_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DvadminManager(object):
    def setupUi(self, DvadminManager):
        DvadminManager.setObjectName("DvadminManager")
        DvadminManager.resize(400, 300)
        DvadminManager.setMinimumSize(QtCore.QSize(400, 300))
        DvadminManager.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(parent=DvadminManager)
        self.label.setGeometry(QtCore.QRect(10, 13, 60, 21))
        self.label.setObjectName("label")
        self.status_label = QtWidgets.QLabel(parent=DvadminManager)
        self.status_label.setGeometry(QtCore.QRect(80, 12, 60, 21))
        self.status_label.setObjectName("status_label")
        self.start_button = QtWidgets.QPushButton(parent=DvadminManager)
        self.start_button.setGeometry(QtCore.QRect(210, 10, 81, 26))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(parent=DvadminManager)
        self.stop_button.setGeometry(QtCore.QRect(310, 9, 81, 26))
        self.stop_button.setObjectName("stop_button")
        self.line = QtWidgets.QFrame(parent=DvadminManager)
        self.line.setGeometry(QtCore.QRect(0, 40, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.log_label = QtWidgets.QTextEdit(parent=DvadminManager)
        self.log_label.setGeometry(QtCore.QRect(-1, 47, 411, 261))
        self.log_label.setObjectName("log_label")

        self.retranslateUi(DvadminManager)
        QtCore.QMetaObject.connectSlotsByName(DvadminManager)

    def retranslateUi(self, DvadminManager):
        _translate = QtCore.QCoreApplication.translate
        DvadminManager.setWindowTitle(_translate("DvadminManager", "服务管理器"))
        self.label.setText(_translate("DvadminManager", "运行状态："))
        self.status_label.setText(_translate("DvadminManager", "未启动"))
        self.start_button.setText(_translate("DvadminManager", "启动服务"))
        self.stop_button.setText(_translate("DvadminManager", "结束服务"))
        self.log_label.setHtml(_translate("DvadminManager", ""))
